siteruffecarde_gestionuser:
    resource: "@SiteruffecardeGestionuserBundle/Controller/"
    type:     annotation
    prefix:   /

siteruffecarde_site:
    resource: "@SiteruffecardeSiteBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

#fosuserBundle
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"